image: node:14-alpine

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          name: check
          script:
            - npm ci
            - npm run check
